server:
  port: 9192

spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:ranjan
  application:
    name: ORDER-SERVICE

  config:
    import: configserver:http://localhost:9196
      
    

#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka
#  instance:
#    hostname: localhost

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  health:
    circuitbreakers:
      enabled: true

 
resilience4j:
  circuitbreaker:
    instances:
      OrderToPayment: 
        register-health-indicator: true
        event-consumer-buffer-size: 10
        failure-rate-threshold: 50
        minimum-number-of-calls: 5
        automatic-transition-from-open-to-half-open-enabled: true
        wait-duration-in-open-state: 5s
        permitted-number-of-calls-in-half-open-state: 3
        sliding-window-size: 10
        sliding-window-type: count-based
        
  retry:
    instances:
      OrderToPayment:
        max-attempts: 3
        wait-duration: 500ms
       
  ratelimiter:
    instances:
      OrderToPayment:
        limit-for-period: 10
       
  bulkhead:
    instances:
      OrderToPayment:
        max-concurrent-calls: 5
        
  timelimiter:
    instances:
      OrderToPayment:
        timeout-duration: 2s
        
  
        